# Generated by Django 5.0.6 on 2024-06-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.AddField(
            model_name='libro',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='libro',
            name='imagen_url',
            field=models.ImageField(upload_to='Libros, null=True'),
        ),
    ]
