# Generated by Django 5.0.6 on 2024-06-29 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Library_app', '0004_alter_libro_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='imagen_url',
            new_name='portada',
        ),
    ]
