# Generated by Django 5.0.6 on 2024-06-30 22:40

import Library_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library_app', '0005_rename_imagen_url_libro_portada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('portada', models.ImageField(null=True, upload_to='productos')),
                ('precio', models.IntegerField(default=Library_app.models.precio_random)),
                ('categoria', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TipoLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Libro',
        ),
        migrations.AddField(
            model_name='producto',
            name='tipolibro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Library_app.tipolibro'),
        ),
    ]
